name: Crawl IQAir Data

on:
  schedule:
    - cron: '0 */1 * * *'  
  workflow_dispatch:  

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  # Token for push permission
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python crawler/checking.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git diff --staged --quiet || git commit -m "Update AQI data at $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
